### ISSUE TITLE
"salary" is not a defined variable in get_exectuvive_compensation.ipynb

### ISSUE THREAD

**Issue by mzhukovs** [rsljr/edgarParser#2]
Nice work, came across from a google search.

FYI there's a variable called "salary" in the file (referenced twice) to do the actual lookup for columns, i believe it's intended to be a regex pattern, but it is not defined anywhere in the notebook file.

Also, typo in the name of the notebook file (get_exectuvive_compensation.ipynb), exectuvive instead of executive.

**Comment by rsljr** [comment]
Thanks, I plan to revamp the notebook and code this year.
