### ISSUE TITLE
Could you let me know where can I get a package for getting the DEF 14A link? 

### ISSUE THREAD

**Issue by Raymond-KT** [rsljr/edgarParser#3]
I'm using edgarParser well. Thank you very much~!
It's beneficial for me!! especially get_executive_compensation function. 

But I want to know about the package to which I can get the DEF 14A link. 
I finded all the sources including GitHub, StackOverflow, and lots of tech blogs, but I can't find the package that I want. 
T-T

Could you let me know where can I get a package for getting the DEF 14A link? 

Thank you.

**Comment by rsljr** [comment]
I use the R package "edgar" to download the SEC master index.

**Comment by Raymond-KT** [comment]
> I use the R package "edgar" to download the SEC master index.

Thank you very much!
I followed your advice and it worked.

I use R package "edgar" and get DEF 14A URL from master index. 

Thank you!
